name: vggt
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - decord==0.6.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - embreex==2.17.7.post6
      - exceptiongroup==1.3.0
      - fastapi==0.116.1
      - ffmpy==0.6.1
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fonttools==4.59.2
      - fsspec==2025.9.0
      - gradio==5.17.1
      - gradio-client==1.7.1
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.1.9
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lightglue==0.0
      - lxml==6.0.1
      - manifold3d==3.2.1
      - mapbox-earcut==1.0.3
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgspec==0.19.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnxruntime==1.22.1
      - opencv-python==4.11.0.86
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.2
      - pillow==11.3.0
      - plyfile==1.1.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - pyceres==2.3
      - pycollada==0.9.2
      - pycolmap==3.10.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.5
      - rich==14.1.0
      - rpds-py==0.27.1
      - rtree==1.4.1
      - ruff==0.12.12
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - shtab==1.7.2
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.47.3
      - svg-path==7.0
      - sympy==1.14.0
      - tifffile==2025.5.10
      - tomlkit==0.13.3
      - torch==2.3.1
      - torchvision==0.18.1
      - tqdm==4.67.1
      - trimesh==4.8.1
      - triton==2.3.1
      - typeguard==4.4.4
      - typer==0.17.4
      - typing-extensions==4.15.0
      - tyro==0.9.31
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - vggt==0.0.1
      - vhacdx==0.0.8.post2
      - viser==0.2.23
      - websockets==14.2
      - xxhash==3.5.0
      - yourdfpy==0.0.58
prefix: /root/.conda/envs/vggt
